// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AlertResponse,
    AlertResponseFromJSON,
    AlertResponseToJSON,
} from '../models/AlertResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type IncrementalAnalysisResponse,
    IncrementalAnalysisResponseFromJSON,
    IncrementalAnalysisResponseToJSON,
} from '../models/IncrementalAnalysisResponse';

export interface AcknowledgeAlertAlertsAlertIdAcknowledgePostRequest {
    alertId: number;
}

export interface GetGroomingAnalysisAlertsAlertIdAnalysisGetRequest {
    alertId: number;
}

/**
 * 
 */
export class AlertsApi extends runtime.BaseAPI {

    /**
     * Creates request options for acknowledgeAlertAlertsAlertIdAcknowledgePost without sending the request
     */
    async acknowledgeAlertAlertsAlertIdAcknowledgePostRequestOpts(requestParameters: AcknowledgeAlertAlertsAlertIdAcknowledgePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['alertId'] == null) {
            throw new runtime.RequiredError(
                'alertId',
                'Required parameter "alertId" was null or undefined when calling acknowledgeAlertAlertsAlertIdAcknowledgePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/alerts/{alert_id}/acknowledge`;
        urlPath = urlPath.replace('{alert_id}', encodeURIComponent(String(requestParameters['alertId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Acknowledge Alert
     */
    async acknowledgeAlertAlertsAlertIdAcknowledgePostRaw(requestParameters: AcknowledgeAlertAlertsAlertIdAcknowledgePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertResponse>> {
        const requestOptions = await this.acknowledgeAlertAlertsAlertIdAcknowledgePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlertResponseFromJSON(jsonValue));
    }

    /**
     * Acknowledge Alert
     */
    async acknowledgeAlertAlertsAlertIdAcknowledgePost(requestParameters: AcknowledgeAlertAlertsAlertIdAcknowledgePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertResponse> {
        const response = await this.acknowledgeAlertAlertsAlertIdAcknowledgePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroomingAnalysisAlertsAlertIdAnalysisGet without sending the request
     */
    async getGroomingAnalysisAlertsAlertIdAnalysisGetRequestOpts(requestParameters: GetGroomingAnalysisAlertsAlertIdAnalysisGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['alertId'] == null) {
            throw new runtime.RequiredError(
                'alertId',
                'Required parameter "alertId" was null or undefined when calling getGroomingAnalysisAlertsAlertIdAnalysisGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/alerts/{alert_id}/analysis`;
        urlPath = urlPath.replace('{alert_id}', encodeURIComponent(String(requestParameters['alertId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get or generate incremental grooming analysis for an alert.  Returns only newly detected stages (empty if none detected or already fully analyzed).
     * Get Grooming Analysis
     */
    async getGroomingAnalysisAlertsAlertIdAnalysisGetRaw(requestParameters: GetGroomingAnalysisAlertsAlertIdAnalysisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncrementalAnalysisResponse>> {
        const requestOptions = await this.getGroomingAnalysisAlertsAlertIdAnalysisGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncrementalAnalysisResponseFromJSON(jsonValue));
    }

    /**
     * Get or generate incremental grooming analysis for an alert.  Returns only newly detected stages (empty if none detected or already fully analyzed).
     * Get Grooming Analysis
     */
    async getGroomingAnalysisAlertsAlertIdAnalysisGet(requestParameters: GetGroomingAnalysisAlertsAlertIdAnalysisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncrementalAnalysisResponse> {
        const response = await this.getGroomingAnalysisAlertsAlertIdAnalysisGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAlertsAlertsGet without sending the request
     */
    async listAlertsAlertsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/alerts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Alerts
     */
    async listAlertsAlertsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlertResponse>>> {
        const requestOptions = await this.listAlertsAlertsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlertResponseFromJSON));
    }

    /**
     * List Alerts
     */
    async listAlertsAlertsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlertResponse>> {
        const response = await this.listAlertsAlertsGetRaw(initOverrides);
        return await response.value();
    }

}
