// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AlertResponse,
    AlertResponseFromJSON,
    AlertResponseToJSON,
} from '../models/AlertResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type IncrementalAnalysisResponse,
    IncrementalAnalysisResponseFromJSON,
    IncrementalAnalysisResponseToJSON,
} from '../models/IncrementalAnalysisResponse';

export interface AcknowledgeAlertApiAlertsAlertIdAcknowledgePostRequest {
    alertId: number;
}

export interface GetGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGetRequest {
    alertId: number;
}

/**
 * 
 */
export class AlertsApi extends runtime.BaseAPI {

    /**
     * Creates request options for acknowledgeAlertApiAlertsAlertIdAcknowledgePost without sending the request
     */
    async acknowledgeAlertApiAlertsAlertIdAcknowledgePostRequestOpts(requestParameters: AcknowledgeAlertApiAlertsAlertIdAcknowledgePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['alertId'] == null) {
            throw new runtime.RequiredError(
                'alertId',
                'Required parameter "alertId" was null or undefined when calling acknowledgeAlertApiAlertsAlertIdAcknowledgePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alerts/{alert_id}/acknowledge`;
        urlPath = urlPath.replace('{alert_id}', encodeURIComponent(String(requestParameters['alertId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Acknowledge Alert
     */
    async acknowledgeAlertApiAlertsAlertIdAcknowledgePostRaw(requestParameters: AcknowledgeAlertApiAlertsAlertIdAcknowledgePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlertResponse>> {
        const requestOptions = await this.acknowledgeAlertApiAlertsAlertIdAcknowledgePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlertResponseFromJSON(jsonValue));
    }

    /**
     * Acknowledge Alert
     */
    async acknowledgeAlertApiAlertsAlertIdAcknowledgePost(requestParameters: AcknowledgeAlertApiAlertsAlertIdAcknowledgePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlertResponse> {
        const response = await this.acknowledgeAlertApiAlertsAlertIdAcknowledgePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGet without sending the request
     */
    async getGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGetRequestOpts(requestParameters: GetGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['alertId'] == null) {
            throw new runtime.RequiredError(
                'alertId',
                'Required parameter "alertId" was null or undefined when calling getGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alerts/{alert_id}/grooming-analysis`;
        urlPath = urlPath.replace('{alert_id}', encodeURIComponent(String(requestParameters['alertId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get or generate incremental grooming analysis for an alert.  Returns only newly detected stages (empty if none detected or already fully analyzed).
     * Get Grooming Analysis
     */
    async getGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGetRaw(requestParameters: GetGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IncrementalAnalysisResponse>> {
        const requestOptions = await this.getGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IncrementalAnalysisResponseFromJSON(jsonValue));
    }

    /**
     * Get or generate incremental grooming analysis for an alert.  Returns only newly detected stages (empty if none detected or already fully analyzed).
     * Get Grooming Analysis
     */
    async getGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGet(requestParameters: GetGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IncrementalAnalysisResponse> {
        const response = await this.getGroomingAnalysisApiAlertsAlertIdGroomingAnalysisGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAlertsApiAlertsGet without sending the request
     */
    async listAlertsApiAlertsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/alerts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Alerts
     */
    async listAlertsApiAlertsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlertResponse>>> {
        const requestOptions = await this.listAlertsApiAlertsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlertResponseFromJSON));
    }

    /**
     * List Alerts
     */
    async listAlertsApiAlertsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlertResponse>> {
        const response = await this.listAlertsApiAlertsGetRaw(initOverrides);
        return await response.value();
    }

}
