// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type ParentLogin,
    ParentLoginFromJSON,
    ParentLoginToJSON,
} from '../models/ParentLogin';
import {
    type ParentRegister,
    ParentRegisterFromJSON,
    ParentRegisterToJSON,
} from '../models/ParentRegister';
import {
    type ParentResponse,
    ParentResponseFromJSON,
    ParentResponseToJSON,
} from '../models/ParentResponse';
import {
    type TokenResponse,
    TokenResponseFromJSON,
    TokenResponseToJSON,
} from '../models/TokenResponse';

export interface LoginParentApiAuthLoginPostRequest {
    parentLogin: ParentLogin;
}

export interface RegisterParentApiAuthRegisterPostRequest {
    parentRegister: ParentRegister;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMeApiAuthMeGet without sending the request
     */
    async getMeApiAuthMeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Me
     */
    async getMeApiAuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ParentResponse>> {
        const requestOptions = await this.getMeApiAuthMeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ParentResponseFromJSON(jsonValue));
    }

    /**
     * Get Me
     */
    async getMeApiAuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ParentResponse> {
        const response = await this.getMeApiAuthMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginParentApiAuthLoginPost without sending the request
     */
    async loginParentApiAuthLoginPostRequestOpts(requestParameters: LoginParentApiAuthLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['parentLogin'] == null) {
            throw new runtime.RequiredError(
                'parentLogin',
                'Required parameter "parentLogin" was null or undefined when calling loginParentApiAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ParentLoginToJSON(requestParameters['parentLogin']),
        };
    }

    /**
     * Login Parent
     */
    async loginParentApiAuthLoginPostRaw(requestParameters: LoginParentApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.loginParentApiAuthLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Login Parent
     */
    async loginParentApiAuthLoginPost(requestParameters: LoginParentApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.loginParentApiAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerParentApiAuthRegisterPost without sending the request
     */
    async registerParentApiAuthRegisterPostRequestOpts(requestParameters: RegisterParentApiAuthRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['parentRegister'] == null) {
            throw new runtime.RequiredError(
                'parentRegister',
                'Required parameter "parentRegister" was null or undefined when calling registerParentApiAuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ParentRegisterToJSON(requestParameters['parentRegister']),
        };
    }

    /**
     * Register Parent
     */
    async registerParentApiAuthRegisterPostRaw(requestParameters: RegisterParentApiAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ParentResponse>> {
        const requestOptions = await this.registerParentApiAuthRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ParentResponseFromJSON(jsonValue));
    }

    /**
     * Register Parent
     */
    async registerParentApiAuthRegisterPost(requestParameters: RegisterParentApiAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ParentResponse> {
        const response = await this.registerParentApiAuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
