// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type ParentLogin,
    ParentLoginFromJSON,
    ParentLoginToJSON,
} from '../models/ParentLogin';
import {
    type ParentRegister,
    ParentRegisterFromJSON,
    ParentRegisterToJSON,
} from '../models/ParentRegister';
import {
    type ParentResponse,
    ParentResponseFromJSON,
    ParentResponseToJSON,
} from '../models/ParentResponse';
import {
    type TokenResponse,
    TokenResponseFromJSON,
    TokenResponseToJSON,
} from '../models/TokenResponse';

export interface LoginParentAuthLoginPostRequest {
    parentLogin: ParentLogin;
}

export interface RegisterParentAuthRegisterPostRequest {
    parentRegister: ParentRegister;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMeAuthMeGet without sending the request
     */
    async getMeAuthMeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Me
     */
    async getMeAuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ParentResponse>> {
        const requestOptions = await this.getMeAuthMeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ParentResponseFromJSON(jsonValue));
    }

    /**
     * Get Me
     */
    async getMeAuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ParentResponse> {
        const response = await this.getMeAuthMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for loginParentAuthLoginPost without sending the request
     */
    async loginParentAuthLoginPostRequestOpts(requestParameters: LoginParentAuthLoginPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['parentLogin'] == null) {
            throw new runtime.RequiredError(
                'parentLogin',
                'Required parameter "parentLogin" was null or undefined when calling loginParentAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ParentLoginToJSON(requestParameters['parentLogin']),
        };
    }

    /**
     * Login Parent
     */
    async loginParentAuthLoginPostRaw(requestParameters: LoginParentAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        const requestOptions = await this.loginParentAuthLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     * Login Parent
     */
    async loginParentAuthLoginPost(requestParameters: LoginParentAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.loginParentAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerParentAuthRegisterPost without sending the request
     */
    async registerParentAuthRegisterPostRequestOpts(requestParameters: RegisterParentAuthRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['parentRegister'] == null) {
            throw new runtime.RequiredError(
                'parentRegister',
                'Required parameter "parentRegister" was null or undefined when calling registerParentAuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ParentRegisterToJSON(requestParameters['parentRegister']),
        };
    }

    /**
     * Register Parent
     */
    async registerParentAuthRegisterPostRaw(requestParameters: RegisterParentAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ParentResponse>> {
        const requestOptions = await this.registerParentAuthRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ParentResponseFromJSON(jsonValue));
    }

    /**
     * Register Parent
     */
    async registerParentAuthRegisterPost(requestParameters: RegisterParentAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ParentResponse> {
        const response = await this.registerParentAuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
