// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChildAccountCreate,
    ChildAccountCreateFromJSON,
    ChildAccountCreateToJSON,
} from '../models/ChildAccountCreate';
import {
    type ChildAccountResponse,
    ChildAccountResponseFromJSON,
    ChildAccountResponseToJSON,
} from '../models/ChildAccountResponse';
import {
    type ChildAccountUpdate,
    ChildAccountUpdateFromJSON,
    ChildAccountUpdateToJSON,
} from '../models/ChildAccountUpdate';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateChildApiChildrenPostRequest {
    childAccountCreate: ChildAccountCreate;
}

export interface DeleteChildApiChildrenChildIdDeleteRequest {
    childId: number;
}

export interface UpdateChildApiChildrenChildIdPutRequest {
    childId: number;
    childAccountUpdate: ChildAccountUpdate;
}

/**
 * 
 */
export class ChildrenApi extends runtime.BaseAPI {

    /**
     * Creates request options for createChildApiChildrenPost without sending the request
     */
    async createChildApiChildrenPostRequestOpts(requestParameters: CreateChildApiChildrenPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childAccountCreate'] == null) {
            throw new runtime.RequiredError(
                'childAccountCreate',
                'Required parameter "childAccountCreate" was null or undefined when calling createChildApiChildrenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/children`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChildAccountCreateToJSON(requestParameters['childAccountCreate']),
        };
    }

    /**
     * Create Child
     */
    async createChildApiChildrenPostRaw(requestParameters: CreateChildApiChildrenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChildAccountResponse>> {
        const requestOptions = await this.createChildApiChildrenPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChildAccountResponseFromJSON(jsonValue));
    }

    /**
     * Create Child
     */
    async createChildApiChildrenPost(requestParameters: CreateChildApiChildrenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChildAccountResponse> {
        const response = await this.createChildApiChildrenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteChildApiChildrenChildIdDelete without sending the request
     */
    async deleteChildApiChildrenChildIdDeleteRequestOpts(requestParameters: DeleteChildApiChildrenChildIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling deleteChildApiChildrenChildIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/children/{child_id}`;
        urlPath = urlPath.replace('{child_id}', encodeURIComponent(String(requestParameters['childId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Child
     */
    async deleteChildApiChildrenChildIdDeleteRaw(requestParameters: DeleteChildApiChildrenChildIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteChildApiChildrenChildIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Child
     */
    async deleteChildApiChildrenChildIdDelete(requestParameters: DeleteChildApiChildrenChildIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteChildApiChildrenChildIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listChildrenApiChildrenGet without sending the request
     */
    async listChildrenApiChildrenGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/children`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Children
     */
    async listChildrenApiChildrenGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChildAccountResponse>>> {
        const requestOptions = await this.listChildrenApiChildrenGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChildAccountResponseFromJSON));
    }

    /**
     * List Children
     */
    async listChildrenApiChildrenGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChildAccountResponse>> {
        const response = await this.listChildrenApiChildrenGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateChildApiChildrenChildIdPut without sending the request
     */
    async updateChildApiChildrenChildIdPutRequestOpts(requestParameters: UpdateChildApiChildrenChildIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling updateChildApiChildrenChildIdPut().'
            );
        }

        if (requestParameters['childAccountUpdate'] == null) {
            throw new runtime.RequiredError(
                'childAccountUpdate',
                'Required parameter "childAccountUpdate" was null or undefined when calling updateChildApiChildrenChildIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/children/{child_id}`;
        urlPath = urlPath.replace('{child_id}', encodeURIComponent(String(requestParameters['childId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChildAccountUpdateToJSON(requestParameters['childAccountUpdate']),
        };
    }

    /**
     * Update Child
     */
    async updateChildApiChildrenChildIdPutRaw(requestParameters: UpdateChildApiChildrenChildIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChildAccountResponse>> {
        const requestOptions = await this.updateChildApiChildrenChildIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChildAccountResponseFromJSON(jsonValue));
    }

    /**
     * Update Child
     */
    async updateChildApiChildrenChildIdPut(requestParameters: UpdateChildApiChildrenChildIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChildAccountResponse> {
        const response = await this.updateChildApiChildrenChildIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
