// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChildAccountCreate,
    ChildAccountCreateFromJSON,
    ChildAccountCreateToJSON,
} from '../models/ChildAccountCreate';
import {
    type ChildAccountResponse,
    ChildAccountResponseFromJSON,
    ChildAccountResponseToJSON,
} from '../models/ChildAccountResponse';
import {
    type ChildAccountUpdate,
    ChildAccountUpdateFromJSON,
    ChildAccountUpdateToJSON,
} from '../models/ChildAccountUpdate';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateChildChildrenPostRequest {
    childAccountCreate: ChildAccountCreate;
}

export interface DeleteChildChildrenChildIdDeleteRequest {
    childId: number;
}

export interface UpdateChildChildrenChildIdPutRequest {
    childId: number;
    childAccountUpdate: ChildAccountUpdate;
}

/**
 * 
 */
export class ChildrenApi extends runtime.BaseAPI {

    /**
     * Creates request options for createChildChildrenPost without sending the request
     */
    async createChildChildrenPostRequestOpts(requestParameters: CreateChildChildrenPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childAccountCreate'] == null) {
            throw new runtime.RequiredError(
                'childAccountCreate',
                'Required parameter "childAccountCreate" was null or undefined when calling createChildChildrenPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/children`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChildAccountCreateToJSON(requestParameters['childAccountCreate']),
        };
    }

    /**
     * Create Child
     */
    async createChildChildrenPostRaw(requestParameters: CreateChildChildrenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChildAccountResponse>> {
        const requestOptions = await this.createChildChildrenPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChildAccountResponseFromJSON(jsonValue));
    }

    /**
     * Create Child
     */
    async createChildChildrenPost(requestParameters: CreateChildChildrenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChildAccountResponse> {
        const response = await this.createChildChildrenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteChildChildrenChildIdDelete without sending the request
     */
    async deleteChildChildrenChildIdDeleteRequestOpts(requestParameters: DeleteChildChildrenChildIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling deleteChildChildrenChildIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/children/{child_id}`;
        urlPath = urlPath.replace('{child_id}', encodeURIComponent(String(requestParameters['childId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Child
     */
    async deleteChildChildrenChildIdDeleteRaw(requestParameters: DeleteChildChildrenChildIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteChildChildrenChildIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Child
     */
    async deleteChildChildrenChildIdDelete(requestParameters: DeleteChildChildrenChildIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteChildChildrenChildIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listChildrenChildrenGet without sending the request
     */
    async listChildrenChildrenGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/children`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Children
     */
    async listChildrenChildrenGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ChildAccountResponse>>> {
        const requestOptions = await this.listChildrenChildrenGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChildAccountResponseFromJSON));
    }

    /**
     * List Children
     */
    async listChildrenChildrenGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ChildAccountResponse>> {
        const response = await this.listChildrenChildrenGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateChildChildrenChildIdPut without sending the request
     */
    async updateChildChildrenChildIdPutRequestOpts(requestParameters: UpdateChildChildrenChildIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling updateChildChildrenChildIdPut().'
            );
        }

        if (requestParameters['childAccountUpdate'] == null) {
            throw new runtime.RequiredError(
                'childAccountUpdate',
                'Required parameter "childAccountUpdate" was null or undefined when calling updateChildChildrenChildIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/children/{child_id}`;
        urlPath = urlPath.replace('{child_id}', encodeURIComponent(String(requestParameters['childId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChildAccountUpdateToJSON(requestParameters['childAccountUpdate']),
        };
    }

    /**
     * Update Child
     */
    async updateChildChildrenChildIdPutRaw(requestParameters: UpdateChildChildrenChildIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChildAccountResponse>> {
        const requestOptions = await this.updateChildChildrenChildIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChildAccountResponseFromJSON(jsonValue));
    }

    /**
     * Update Child
     */
    async updateChildChildrenChildIdPut(requestParameters: UpdateChildChildrenChildIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChildAccountResponse> {
        const response = await this.updateChildChildrenChildIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
