// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ClassifierCheckInRequest,
    ClassifierCheckInRequestFromJSON,
    ClassifierCheckInRequestToJSON,
} from '../models/ClassifierCheckInRequest';
import {
    type ClassifierCheckInResponse,
    ClassifierCheckInResponseFromJSON,
    ClassifierCheckInResponseToJSON,
} from '../models/ClassifierCheckInResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface ClassifierCheckinCheckinPostRequest {
    classifierCheckInRequest: ClassifierCheckInRequest;
    xPassword?: string | null;
}

/**
 * 
 */
export class ClassifierApi extends runtime.BaseAPI {

    /**
     * Creates request options for classifierCheckinCheckinPost without sending the request
     */
    async classifierCheckinCheckinPostRequestOpts(requestParameters: ClassifierCheckinCheckinPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['classifierCheckInRequest'] == null) {
            throw new runtime.RequiredError(
                'classifierCheckInRequest',
                'Required parameter "classifierCheckInRequest" was null or undefined when calling classifierCheckinCheckinPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xPassword'] != null) {
            headerParameters['X-Password'] = String(requestParameters['xPassword']);
        }


        let urlPath = `/checkin`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClassifierCheckInRequestToJSON(requestParameters['classifierCheckInRequest']),
        };
    }

    /**
     * Classifier Checkin
     */
    async classifierCheckinCheckinPostRaw(requestParameters: ClassifierCheckinCheckinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClassifierCheckInResponse>> {
        const requestOptions = await this.classifierCheckinCheckinPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClassifierCheckInResponseFromJSON(jsonValue));
    }

    /**
     * Classifier Checkin
     */
    async classifierCheckinCheckinPost(requestParameters: ClassifierCheckinCheckinPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClassifierCheckInResponse> {
        const response = await this.classifierCheckinCheckinPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
