// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type FlaggedUser,
    FlaggedUserFromJSON,
    FlaggedUserToJSON,
} from '../models/FlaggedUser';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type IngestRequest,
    IngestRequestFromJSON,
    IngestRequestToJSON,
} from '../models/IngestRequest';
import {
    type IngestResponse,
    IngestResponseFromJSON,
    IngestResponseToJSON,
} from '../models/IngestResponse';

export interface IngestApiIngestPostRequest {
    ingestRequest: IngestRequest;
}

export interface ListFlagsApiFlagsGetRequest {
    resolved?: boolean | null;
}

export interface ResolveFlagApiFlagsUserIdResolvePostRequest {
    userId: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for ingestApiIngestPost without sending the request
     */
    async ingestApiIngestPostRequestOpts(requestParameters: IngestApiIngestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ingestRequest'] == null) {
            throw new runtime.RequiredError(
                'ingestRequest',
                'Required parameter "ingestRequest" was null or undefined when calling ingestApiIngestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ingest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IngestRequestToJSON(requestParameters['ingestRequest']),
        };
    }

    /**
     * Ingest
     */
    async ingestApiIngestPostRaw(requestParameters: IngestApiIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IngestResponse>> {
        const requestOptions = await this.ingestApiIngestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IngestResponseFromJSON(jsonValue));
    }

    /**
     * Ingest
     */
    async ingestApiIngestPost(requestParameters: IngestApiIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IngestResponse> {
        const response = await this.ingestApiIngestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFlagsApiFlagsGet without sending the request
     */
    async listFlagsApiFlagsGetRequestOpts(requestParameters: ListFlagsApiFlagsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['resolved'] != null) {
            queryParameters['resolved'] = requestParameters['resolved'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/flags`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Flags
     */
    async listFlagsApiFlagsGetRaw(requestParameters: ListFlagsApiFlagsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FlaggedUser>>> {
        const requestOptions = await this.listFlagsApiFlagsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FlaggedUserFromJSON));
    }

    /**
     * List Flags
     */
    async listFlagsApiFlagsGet(requestParameters: ListFlagsApiFlagsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FlaggedUser>> {
        const response = await this.listFlagsApiFlagsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resolveFlagApiFlagsUserIdResolvePost without sending the request
     */
    async resolveFlagApiFlagsUserIdResolvePostRequestOpts(requestParameters: ResolveFlagApiFlagsUserIdResolvePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling resolveFlagApiFlagsUserIdResolvePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/flags/{user_id}/resolve`;
        urlPath = urlPath.replace('{user_id}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resolve Flag
     */
    async resolveFlagApiFlagsUserIdResolvePostRaw(requestParameters: ResolveFlagApiFlagsUserIdResolvePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.resolveFlagApiFlagsUserIdResolvePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Resolve Flag
     */
    async resolveFlagApiFlagsUserIdResolvePost(requestParameters: ResolveFlagApiFlagsUserIdResolvePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.resolveFlagApiFlagsUserIdResolvePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
