// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type IngestRequest,
    IngestRequestFromJSON,
    IngestRequestToJSON,
} from '../models/IngestRequest';

export interface IngestMessageIngestPostRequest {
    ingestRequest: IngestRequest;
}

/**
 * 
 */
export class MessageApi extends runtime.BaseAPI {

    /**
     * Creates request options for ingestMessageIngestPost without sending the request
     */
    async ingestMessageIngestPostRequestOpts(requestParameters: IngestMessageIngestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ingestRequest'] == null) {
            throw new runtime.RequiredError(
                'ingestRequest',
                'Required parameter "ingestRequest" was null or undefined when calling ingestMessageIngestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/message/ingest`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IngestRequestToJSON(requestParameters['ingestRequest']),
        };
    }

    /**
     * Ingest
     */
    async ingestMessageIngestPostRaw(requestParameters: IngestMessageIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestMessageIngestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ingest
     */
    async ingestMessageIngestPost(requestParameters: IngestMessageIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestMessageIngestPostRaw(requestParameters, initOverrides);
    }

}
