// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessageResponse } from './ChatMessageResponse';
import {
    ChatMessageResponseFromJSON,
    ChatMessageResponseFromJSONTyped,
    ChatMessageResponseToJSON,
    ChatMessageResponseToJSONTyped,
} from './ChatMessageResponse';
import type { ChatPlatform } from './ChatPlatform';
import {
    ChatPlatformFromJSON,
    ChatPlatformFromJSONTyped,
    ChatPlatformToJSON,
    ChatPlatformToJSONTyped,
} from './ChatPlatform';

/**
 * 
 * @export
 * @interface AlertResponse
 */
export interface AlertResponse {
    /**
     * 
     * @type {number}
     * @memberof AlertResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof AlertResponse
     */
    childAccountId: number;
    /**
     * 
     * @type {ChatPlatform}
     * @memberof AlertResponse
     */
    platform: ChatPlatform;
    /**
     * 
     * @type {string}
     * @memberof AlertResponse
     */
    serverId: string;
    /**
     * 
     * @type {string}
     * @memberof AlertResponse
     */
    messagePreview: string;
    /**
     * 
     * @type {boolean}
     * @memberof AlertResponse
     */
    acknowledged: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AlertResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<ChatMessageResponse>}
     * @memberof AlertResponse
     */
    messages?: Array<ChatMessageResponse>;
}



/**
 * Check if a given object implements the AlertResponse interface.
 */
export function instanceOfAlertResponse(value: object): value is AlertResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('childAccountId' in value) && !('child_account_id' in value)) || (value['childAccountId'] === undefined && value['child_account_id'] === undefined)) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if ((!('serverId' in value) && !('server_id' in value)) || (value['serverId'] === undefined && value['server_id'] === undefined)) return false;
    if ((!('messagePreview' in value) && !('message_preview' in value)) || (value['messagePreview'] === undefined && value['message_preview'] === undefined)) return false;
    if (!('acknowledged' in value) || value['acknowledged'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function AlertResponseFromJSON(json: any): AlertResponse {
    return AlertResponseFromJSONTyped(json, false);
}

export function AlertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'childAccountId': json['child_account_id'],
        'platform': ChatPlatformFromJSON(json['platform']),
        'serverId': json['server_id'],
        'messagePreview': json['message_preview'],
        'acknowledged': json['acknowledged'],
        'createdAt': (new Date(json['created_at'])),
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(ChatMessageResponseFromJSON)),
    };
}

export function AlertResponseToJSON(json: any): AlertResponse {
    return AlertResponseToJSONTyped(json, false);
}

export function AlertResponseToJSONTyped(value?: AlertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'child_account_id': value['childAccountId'],
        'platform': ChatPlatformToJSON(value['platform']),
        'server_id': value['serverId'],
        'message_preview': value['messagePreview'],
        'acknowledged': value['acknowledged'],
        'created_at': value['createdAt'].toISOString(),
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(ChatMessageResponseToJSON)),
    };
}

