// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageResponse
 */
export interface ChatMessageResponse {
    /**
     * 
     * @type {number}
     * @memberof ChatMessageResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageResponse
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ChatMessageResponse interface.
 */
export function instanceOfChatMessageResponse(value: object): value is ChatMessageResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('userId' in value) && !('user_id' in value)) || (value['userId'] === undefined && value['user_id'] === undefined)) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function ChatMessageResponseFromJSON(json: any): ChatMessageResponse {
    return ChatMessageResponseFromJSONTyped(json, false);
}

export function ChatMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'content': json['content'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ChatMessageResponseToJSON(json: any): ChatMessageResponse {
    return ChatMessageResponseToJSONTyped(json, false);
}

export function ChatMessageResponseToJSONTyped(value?: ChatMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'content': value['content'],
        'created_at': value['createdAt'].toISOString(),
    };
}

