// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChildAccountUpdate
 */
export interface ChildAccountUpdate {
    /**
     * 
     * @type {string}
     * @memberof ChildAccountUpdate
     */
    platformUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChildAccountUpdate
     */
    displayName?: string | null;
}

/**
 * Check if a given object implements the ChildAccountUpdate interface.
 */
export function instanceOfChildAccountUpdate(value: object): value is ChildAccountUpdate {
    return true;
}

export function ChildAccountUpdateFromJSON(json: any): ChildAccountUpdate {
    return ChildAccountUpdateFromJSONTyped(json, false);
}

export function ChildAccountUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildAccountUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'platformUserId': json['platform_user_id'] == null ? undefined : json['platform_user_id'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
    };
}

export function ChildAccountUpdateToJSON(json: any): ChildAccountUpdate {
    return ChildAccountUpdateToJSONTyped(json, false);
}

export function ChildAccountUpdateToJSONTyped(value?: ChildAccountUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform_user_id': value['platformUserId'],
        'display_name': value['displayName'],
    };
}

