// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatPlatform } from './ChatPlatform';
import {
    ChatPlatformFromJSON,
    ChatPlatformFromJSONTyped,
    ChatPlatformToJSON,
    ChatPlatformToJSONTyped,
} from './ChatPlatform';

/**
 * 
 * @export
 * @interface ChildAccountCreate
 */
export interface ChildAccountCreate {
    /**
     * 
     * @type {ChatPlatform}
     * @memberof ChildAccountCreate
     */
    platform: ChatPlatform;
    /**
     * 
     * @type {string}
     * @memberof ChildAccountCreate
     */
    platformUserId: string;
    /**
     * 
     * @type {string}
     * @memberof ChildAccountCreate
     */
    displayName?: string | null;
}



/**
 * Check if a given object implements the ChildAccountCreate interface.
 */
export function instanceOfChildAccountCreate(value: object): value is ChildAccountCreate {
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if ((!('platformUserId' in value) && !('platform_user_id' in value)) || (value['platformUserId'] === undefined && value['platform_user_id'] === undefined)) return false;
    return true;
}

export function ChildAccountCreateFromJSON(json: any): ChildAccountCreate {
    return ChildAccountCreateFromJSONTyped(json, false);
}

export function ChildAccountCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildAccountCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'platform': ChatPlatformFromJSON(json['platform']),
        'platformUserId': json['platform_user_id'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
    };
}

export function ChildAccountCreateToJSON(json: any): ChildAccountCreate {
    return ChildAccountCreateToJSONTyped(json, false);
}

export function ChildAccountCreateToJSONTyped(value?: ChildAccountCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform': ChatPlatformToJSON(value['platform']),
        'platform_user_id': value['platformUserId'],
        'display_name': value['displayName'],
    };
}

