// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassifierCheckInRequest
 */
export interface ClassifierCheckInRequest {
    /**
     * 
     * @type {string}
     * @memberof ClassifierCheckInRequest
     */
    client: string;
    /**
     * 
     * @type {string}
     * @memberof ClassifierCheckInRequest
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof ClassifierCheckInRequest
     */
    timestamp: string;
}

/**
 * Check if a given object implements the ClassifierCheckInRequest interface.
 */
export function instanceOfClassifierCheckInRequest(value: object): value is ClassifierCheckInRequest {
    if (!('client' in value) || value['client'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ClassifierCheckInRequestFromJSON(json: any): ClassifierCheckInRequest {
    return ClassifierCheckInRequestFromJSONTyped(json, false);
}

export function ClassifierCheckInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassifierCheckInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client': json['client'],
        'version': json['version'],
        'timestamp': json['timestamp'],
    };
}

export function ClassifierCheckInRequestToJSON(json: any): ClassifierCheckInRequest {
    return ClassifierCheckInRequestToJSONTyped(json, false);
}

export function ClassifierCheckInRequestToJSONTyped(value?: ClassifierCheckInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client': value['client'],
        'version': value['version'],
        'timestamp': value['timestamp'],
    };
}

