// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassifierCheckInResponse
 */
export interface ClassifierCheckInResponse {
    /**
     * 
     * @type {ClassifierCheckInResponseStatusEnum}
     * @memberof ClassifierCheckInResponse
     */
    status?: ClassifierCheckInResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ClassifierCheckInResponse
     */
    message?: string;
}


/**
 * @export
 */
export const ClassifierCheckInResponseStatusEnum = {
    Ok: 'ok'
} as const;
export type ClassifierCheckInResponseStatusEnum = typeof ClassifierCheckInResponseStatusEnum[keyof typeof ClassifierCheckInResponseStatusEnum];


/**
 * Check if a given object implements the ClassifierCheckInResponse interface.
 */
export function instanceOfClassifierCheckInResponse(value: object): value is ClassifierCheckInResponse {
    return true;
}

export function ClassifierCheckInResponseFromJSON(json: any): ClassifierCheckInResponse {
    return ClassifierCheckInResponseFromJSONTyped(json, false);
}

export function ClassifierCheckInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassifierCheckInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ClassifierCheckInResponseToJSON(json: any): ClassifierCheckInResponse {
    return ClassifierCheckInResponseToJSONTyped(json, false);
}

export function ClassifierCheckInResponseToJSONTyped(value?: ClassifierCheckInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

