// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseStatus } from './ResponseStatus';
import {
    ResponseStatusFromJSON,
    ResponseStatusFromJSONTyped,
    ResponseStatusToJSON,
    ResponseStatusToJSONTyped,
} from './ResponseStatus';

/**
 * 
 * @export
 * @interface ClassifierCheckInResponse
 */
export interface ClassifierCheckInResponse {
    /**
     * 
     * @type {ResponseStatus}
     * @memberof ClassifierCheckInResponse
     */
    status: ResponseStatus;
    /**
     * 
     * @type {string}
     * @memberof ClassifierCheckInResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassifierCheckInResponse
     */
    token: string;
}



/**
 * Check if a given object implements the ClassifierCheckInResponse interface.
 */
export function instanceOfClassifierCheckInResponse(value: object): value is ClassifierCheckInResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function ClassifierCheckInResponseFromJSON(json: any): ClassifierCheckInResponse {
    return ClassifierCheckInResponseFromJSONTyped(json, false);
}

export function ClassifierCheckInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassifierCheckInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': ResponseStatusFromJSON(json['status']),
        'message': json['message'] == null ? undefined : json['message'],
        'token': json['token'],
    };
}

export function ClassifierCheckInResponseToJSON(json: any): ClassifierCheckInResponse {
    return ClassifierCheckInResponseToJSONTyped(json, false);
}

export function ClassifierCheckInResponseToJSONTyped(value?: ClassifierCheckInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ResponseStatusToJSON(value['status']),
        'message': value['message'],
        'token': value['token'],
    };
}

