// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigUpdate
 */
export interface ConfigUpdate {
    /**
     * 
     * @type {string}
     * @memberof ConfigUpdate
     */
    proxyUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigUpdate
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigUpdate
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigUpdate
     */
    localUrl: string;
}

/**
 * Check if a given object implements the ConfigUpdate interface.
 */
export function instanceOfConfigUpdate(value: object): value is ConfigUpdate {
    if ((!('proxyUrl' in value) && !('proxy_url' in value)) || (value['proxyUrl'] === undefined && value['proxy_url'] === undefined)) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if ((!('localUrl' in value) && !('local_url' in value)) || (value['localUrl'] === undefined && value['local_url'] === undefined)) return false;
    return true;
}

export function ConfigUpdateFromJSON(json: any): ConfigUpdate {
    return ConfigUpdateFromJSONTyped(json, false);
}

export function ConfigUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'proxyUrl': json['proxy_url'],
        'username': json['username'],
        'password': json['password'],
        'localUrl': json['local_url'],
    };
}

export function ConfigUpdateToJSON(json: any): ConfigUpdate {
    return ConfigUpdateToJSONTyped(json, false);
}

export function ConfigUpdateToJSONTyped(value?: ConfigUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proxy_url': value['proxyUrl'],
        'username': value['username'],
        'password': value['password'],
        'local_url': value['localUrl'],
    };
}

