// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroomingAnalysis } from './GroomingAnalysis';
import {
    GroomingAnalysisFromJSON,
    GroomingAnalysisFromJSONTyped,
    GroomingAnalysisToJSON,
    GroomingAnalysisToJSONTyped,
} from './GroomingAnalysis';

/**
 * 
 * @export
 * @interface FlaggedConversation
 */
export interface FlaggedConversation {
    /**
     * 
     * @type {string}
     * @memberof FlaggedConversation
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof FlaggedConversation
     */
    serverId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FlaggedConversation
     */
    flaggedChats: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof FlaggedConversation
     */
    resolved: boolean;
    /**
     * 
     * @type {GroomingAnalysis}
     * @memberof FlaggedConversation
     */
    explanation?: GroomingAnalysis | null;
}

/**
 * Check if a given object implements the FlaggedConversation interface.
 */
export function instanceOfFlaggedConversation(value: object): value is FlaggedConversation {
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if ((!('serverId' in value) && !('server_id' in value)) || (value['serverId'] === undefined && value['server_id'] === undefined)) return false;
    if ((!('flaggedChats' in value) && !('flagged_chats' in value)) || (value['flaggedChats'] === undefined && value['flagged_chats'] === undefined)) return false;
    if (!('resolved' in value) || value['resolved'] === undefined) return false;
    return true;
}

export function FlaggedConversationFromJSON(json: any): FlaggedConversation {
    return FlaggedConversationFromJSONTyped(json, false);
}

export function FlaggedConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlaggedConversation {
    if (json == null) {
        return json;
    }
    return {
        
        'platform': json['platform'],
        'serverId': json['server_id'],
        'flaggedChats': json['flagged_chats'],
        'resolved': json['resolved'],
        'explanation': json['explanation'] == null ? undefined : GroomingAnalysisFromJSON(json['explanation']),
    };
}

export function FlaggedConversationToJSON(json: any): FlaggedConversation {
    return FlaggedConversationToJSONTyped(json, false);
}

export function FlaggedConversationToJSONTyped(value?: FlaggedConversation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform': value['platform'],
        'server_id': value['serverId'],
        'flagged_chats': value['flaggedChats'],
        'resolved': value['resolved'],
        'explanation': GroomingAnalysisToJSON(value['explanation']),
    };
}

