// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlaggedUser
 */
export interface FlaggedUser {
    /**
     * 
     * @type {string}
     * @memberof FlaggedUser
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof FlaggedUser
     */
    serverId: string;
    /**
     * 
     * @type {string}
     * @memberof FlaggedUser
     */
    platform: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FlaggedUser
     */
    flaggedChats: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof FlaggedUser
     */
    resolved: boolean;
}

/**
 * Check if a given object implements the FlaggedUser interface.
 */
export function instanceOfFlaggedUser(value: object): value is FlaggedUser {
    if ((!('userId' in value) && !('user_id' in value)) || (value['userId'] === undefined && value['user_id'] === undefined)) return false;
    if ((!('serverId' in value) && !('server_id' in value)) || (value['serverId'] === undefined && value['server_id'] === undefined)) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if ((!('flaggedChats' in value) && !('flagged_chats' in value)) || (value['flaggedChats'] === undefined && value['flagged_chats'] === undefined)) return false;
    if (!('resolved' in value) || value['resolved'] === undefined) return false;
    return true;
}

export function FlaggedUserFromJSON(json: any): FlaggedUser {
    return FlaggedUserFromJSONTyped(json, false);
}

export function FlaggedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlaggedUser {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'serverId': json['server_id'],
        'platform': json['platform'],
        'flaggedChats': json['flagged_chats'],
        'resolved': json['resolved'],
    };
}

export function FlaggedUserToJSON(json: any): FlaggedUser {
    return FlaggedUserToJSONTyped(json, false);
}

export function FlaggedUserToJSONTyped(value?: FlaggedUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'server_id': value['serverId'],
        'platform': value['platform'],
        'flagged_chats': value['flaggedChats'],
        'resolved': value['resolved'],
    };
}

