// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StageAssessment } from './StageAssessment';
import {
    StageAssessmentFromJSON,
    StageAssessmentFromJSONTyped,
    StageAssessmentToJSON,
    StageAssessmentToJSONTyped,
} from './StageAssessment';
import type { OverallAssessment } from './OverallAssessment';
import {
    OverallAssessmentFromJSON,
    OverallAssessmentFromJSONTyped,
    OverallAssessmentToJSON,
    OverallAssessmentToJSONTyped,
} from './OverallAssessment';

/**
 * 
 * @export
 * @interface GroomingAnalysis
 */
export interface GroomingAnalysis {
    /**
     * 
     * @type {StageAssessment}
     * @memberof GroomingAnalysis
     */
    victimSelection: StageAssessment;
    /**
     * 
     * @type {StageAssessment}
     * @memberof GroomingAnalysis
     */
    accessRelationshipBuilding: StageAssessment;
    /**
     * 
     * @type {StageAssessment}
     * @memberof GroomingAnalysis
     */
    trustDevelopment: StageAssessment;
    /**
     * 
     * @type {StageAssessment}
     * @memberof GroomingAnalysis
     */
    isolation: StageAssessment;
    /**
     * 
     * @type {StageAssessment}
     * @memberof GroomingAnalysis
     */
    boundaryTesting: StageAssessment;
    /**
     * 
     * @type {StageAssessment}
     * @memberof GroomingAnalysis
     */
    desensitization: StageAssessment;
    /**
     * 
     * @type {StageAssessment}
     * @memberof GroomingAnalysis
     */
    maintainingControl: StageAssessment;
    /**
     * 
     * @type {OverallAssessment}
     * @memberof GroomingAnalysis
     */
    overallAssessment: OverallAssessment;
}

/**
 * Check if a given object implements the GroomingAnalysis interface.
 */
export function instanceOfGroomingAnalysis(value: object): value is GroomingAnalysis {
    if ((!('victimSelection' in value) && !('victim_selection' in value)) || (value['victimSelection'] === undefined && value['victim_selection'] === undefined)) return false;
    if ((!('accessRelationshipBuilding' in value) && !('access_relationship_building' in value)) || (value['accessRelationshipBuilding'] === undefined && value['access_relationship_building'] === undefined)) return false;
    if ((!('trustDevelopment' in value) && !('trust_development' in value)) || (value['trustDevelopment'] === undefined && value['trust_development'] === undefined)) return false;
    if (!('isolation' in value) || value['isolation'] === undefined) return false;
    if ((!('boundaryTesting' in value) && !('boundary_testing' in value)) || (value['boundaryTesting'] === undefined && value['boundary_testing'] === undefined)) return false;
    if (!('desensitization' in value) || value['desensitization'] === undefined) return false;
    if ((!('maintainingControl' in value) && !('maintaining_control' in value)) || (value['maintainingControl'] === undefined && value['maintaining_control'] === undefined)) return false;
    if ((!('overallAssessment' in value) && !('overall_assessment' in value)) || (value['overallAssessment'] === undefined && value['overall_assessment'] === undefined)) return false;
    return true;
}

export function GroomingAnalysisFromJSON(json: any): GroomingAnalysis {
    return GroomingAnalysisFromJSONTyped(json, false);
}

export function GroomingAnalysisFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroomingAnalysis {
    if (json == null) {
        return json;
    }
    return {
        
        'victimSelection': StageAssessmentFromJSON(json['victim_selection']),
        'accessRelationshipBuilding': StageAssessmentFromJSON(json['access_relationship_building']),
        'trustDevelopment': StageAssessmentFromJSON(json['trust_development']),
        'isolation': StageAssessmentFromJSON(json['isolation']),
        'boundaryTesting': StageAssessmentFromJSON(json['boundary_testing']),
        'desensitization': StageAssessmentFromJSON(json['desensitization']),
        'maintainingControl': StageAssessmentFromJSON(json['maintaining_control']),
        'overallAssessment': OverallAssessmentFromJSON(json['overall_assessment']),
    };
}

export function GroomingAnalysisToJSON(json: any): GroomingAnalysis {
    return GroomingAnalysisToJSONTyped(json, false);
}

export function GroomingAnalysisToJSONTyped(value?: GroomingAnalysis | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'victim_selection': StageAssessmentToJSON(value['victimSelection']),
        'access_relationship_building': StageAssessmentToJSON(value['accessRelationshipBuilding']),
        'trust_development': StageAssessmentToJSON(value['trustDevelopment']),
        'isolation': StageAssessmentToJSON(value['isolation']),
        'boundary_testing': StageAssessmentToJSON(value['boundaryTesting']),
        'desensitization': StageAssessmentToJSON(value['desensitization']),
        'maintaining_control': StageAssessmentToJSON(value['maintainingControl']),
        'overall_assessment': OverallAssessmentToJSON(value['overallAssessment']),
    };
}

