// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewlyDetectedStage } from './NewlyDetectedStage';
import {
    NewlyDetectedStageFromJSON,
    NewlyDetectedStageFromJSONTyped,
    NewlyDetectedStageToJSON,
    NewlyDetectedStageToJSONTyped,
} from './NewlyDetectedStage';

/**
 * Response from incremental grooming analysis.
 * @export
 * @interface IncrementalAnalysisResponse
 */
export interface IncrementalAnalysisResponse {
    /**
     * Newly detected stages in this analysis
     * @type {Array<NewlyDetectedStage>}
     * @memberof IncrementalAnalysisResponse
     */
    newStages?: Array<NewlyDetectedStage>;
}

/**
 * Check if a given object implements the IncrementalAnalysisResponse interface.
 */
export function instanceOfIncrementalAnalysisResponse(value: object): value is IncrementalAnalysisResponse {
    return true;
}

export function IncrementalAnalysisResponseFromJSON(json: any): IncrementalAnalysisResponse {
    return IncrementalAnalysisResponseFromJSONTyped(json, false);
}

export function IncrementalAnalysisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncrementalAnalysisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'newStages': json['new_stages'] == null ? undefined : ((json['new_stages'] as Array<any>).map(NewlyDetectedStageFromJSON)),
    };
}

export function IncrementalAnalysisResponseToJSON(json: any): IncrementalAnalysisResponse {
    return IncrementalAnalysisResponseToJSONTyped(json, false);
}

export function IncrementalAnalysisResponseToJSONTyped(value?: IncrementalAnalysisResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_stages': value['newStages'] == null ? undefined : ((value['newStages'] as Array<any>).map(NewlyDetectedStageToJSON)),
    };
}

