// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestResponse
 */
export interface IngestResponse {
    /**
     * 
     * @type {string}
     * @memberof IngestResponse
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof IngestResponse
     */
    classifiedCount: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof IngestResponse
     */
    newlyFlagged: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof IngestResponse
     */
    parentsNotified?: number;
}

/**
 * Check if a given object implements the IngestResponse interface.
 */
export function instanceOfIngestResponse(value: object): value is IngestResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('classifiedCount' in value) && !('classified_count' in value)) || (value['classifiedCount'] === undefined && value['classified_count'] === undefined)) return false;
    if ((!('newlyFlagged' in value) && !('newly_flagged' in value)) || (value['newlyFlagged'] === undefined && value['newly_flagged'] === undefined)) return false;
    return true;
}

export function IngestResponseFromJSON(json: any): IngestResponse {
    return IngestResponseFromJSONTyped(json, false);
}

export function IngestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'classifiedCount': json['classified_count'],
        'newlyFlagged': json['newly_flagged'],
        'parentsNotified': json['parents_notified'] == null ? undefined : json['parents_notified'],
    };
}

export function IngestResponseToJSON(json: any): IngestResponse {
    return IngestResponseToJSONTyped(json, false);
}

export function IngestResponseToJSONTyped(value?: IngestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'classified_count': value['classifiedCount'],
        'newly_flagged': value['newlyFlagged'],
        'parents_notified': value['parentsNotified'],
    };
}

