// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestRequest
 */
export interface IngestRequest {
    /**
     * 
     * @type {string}
     * @memberof IngestRequest
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof IngestRequest
     */
    serverId: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof IngestRequest
     */
    chatGroup: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the IngestRequest interface.
 */
export function instanceOfIngestRequest(value: object): value is IngestRequest {
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if ((!('serverId' in value) && !('server_id' in value)) || (value['serverId'] === undefined && value['server_id'] === undefined)) return false;
    if ((!('chatGroup' in value) && !('chat_group' in value)) || (value['chatGroup'] === undefined && value['chat_group'] === undefined)) return false;
    return true;
}

export function IngestRequestFromJSON(json: any): IngestRequest {
    return IngestRequestFromJSONTyped(json, false);
}

export function IngestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'platform': json['platform'],
        'serverId': json['server_id'],
        'chatGroup': json['chat_group'],
    };
}

export function IngestRequestToJSON(json: any): IngestRequest {
    return IngestRequestToJSONTyped(json, false);
}

export function IngestRequestToJSONTyped(value?: IngestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform': value['platform'],
        'server_id': value['serverId'],
        'chat_group': value['chatGroup'],
    };
}

