// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatPlatform } from './ChatPlatform';
import {
    ChatPlatformFromJSON,
    ChatPlatformFromJSONTyped,
    ChatPlatformToJSON,
    ChatPlatformToJSONTyped,
} from './ChatPlatform';

/**
 * 
 * @export
 * @interface IngestRequest
 */
export interface IngestRequest {
    /**
     * 
     * @type {ChatPlatform}
     * @memberof IngestRequest
     */
    platform: ChatPlatform;
    /**
     * 
     * @type {string}
     * @memberof IngestRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof IngestRequest
     */
    serverId: string;
    /**
     * 
     * @type {string}
     * @memberof IngestRequest
     */
    message: string;
}



/**
 * Check if a given object implements the IngestRequest interface.
 */
export function instanceOfIngestRequest(value: object): value is IngestRequest {
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if ((!('userId' in value) && !('user_id' in value)) || (value['userId'] === undefined && value['user_id'] === undefined)) return false;
    if ((!('serverId' in value) && !('server_id' in value)) || (value['serverId'] === undefined && value['server_id'] === undefined)) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function IngestRequestFromJSON(json: any): IngestRequest {
    return IngestRequestFromJSONTyped(json, false);
}

export function IngestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'platform': ChatPlatformFromJSON(json['platform']),
        'userId': json['user_id'],
        'serverId': json['server_id'],
        'message': json['message'],
    };
}

export function IngestRequestToJSON(json: any): IngestRequest {
    return IngestRequestToJSONTyped(json, false);
}

export function IngestRequestToJSONTyped(value?: IngestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform': ChatPlatformToJSON(value['platform']),
        'user_id': value['userId'],
        'server_id': value['serverId'],
        'message': value['message'],
    };
}

