// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A newly detected grooming stage with minimal evidence.
 * @export
 * @interface NewlyDetectedStage
 */
export interface NewlyDetectedStage {
    /**
     * The stage name that was detected
     * @type {string}
     * @memberof NewlyDetectedStage
     */
    stage: string;
    /**
     * High | Medium | Low
     * @type {string}
     * @memberof NewlyDetectedStage
     */
    confidence: string;
    /**
     * The ChatMessage ID with strongest evidence
     * @type {number}
     * @memberof NewlyDetectedStage
     */
    messageId: number;
}

/**
 * Check if a given object implements the NewlyDetectedStage interface.
 */
export function instanceOfNewlyDetectedStage(value: object): value is NewlyDetectedStage {
    if (!('stage' in value) || value['stage'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if ((!('messageId' in value) && !('message_id' in value)) || (value['messageId'] === undefined && value['message_id'] === undefined)) return false;
    return true;
}

export function NewlyDetectedStageFromJSON(json: any): NewlyDetectedStage {
    return NewlyDetectedStageFromJSONTyped(json, false);
}

export function NewlyDetectedStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewlyDetectedStage {
    if (json == null) {
        return json;
    }
    return {
        
        'stage': json['stage'],
        'confidence': json['confidence'],
        'messageId': json['message_id'],
    };
}

export function NewlyDetectedStageToJSON(json: any): NewlyDetectedStage {
    return NewlyDetectedStageToJSONTyped(json, false);
}

export function NewlyDetectedStageToJSONTyped(value?: NewlyDetectedStage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stage': value['stage'],
        'confidence': value['confidence'],
        'message_id': value['messageId'],
    };
}

