// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverallAssessment
 */
export interface OverallAssessment {
    /**
     * 
     * @type {number}
     * @memberof OverallAssessment
     */
    observedStageCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof OverallAssessment
     */
    stageOrder?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OverallAssessment
     */
    behavioralProgression?: string;
    /**
     * 
     * @type {string}
     * @memberof OverallAssessment
     */
    uncertainties?: string;
    /**
     * 
     * @type {string}
     * @memberof OverallAssessment
     */
    summary?: string;
}

/**
 * Check if a given object implements the OverallAssessment interface.
 */
export function instanceOfOverallAssessment(value: object): value is OverallAssessment {
    return true;
}

export function OverallAssessmentFromJSON(json: any): OverallAssessment {
    return OverallAssessmentFromJSONTyped(json, false);
}

export function OverallAssessmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverallAssessment {
    if (json == null) {
        return json;
    }
    return {
        
        'observedStageCount': json['observed_stage_count'] == null ? undefined : json['observed_stage_count'],
        'stageOrder': json['stage_order'] == null ? undefined : json['stage_order'],
        'behavioralProgression': json['behavioral_progression'] == null ? undefined : json['behavioral_progression'],
        'uncertainties': json['uncertainties'] == null ? undefined : json['uncertainties'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function OverallAssessmentToJSON(json: any): OverallAssessment {
    return OverallAssessmentToJSONTyped(json, false);
}

export function OverallAssessmentToJSONTyped(value?: OverallAssessment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'observed_stage_count': value['observedStageCount'],
        'stage_order': value['stageOrder'],
        'behavioral_progression': value['behavioralProgression'],
        'uncertainties': value['uncertainties'],
        'summary': value['summary'],
    };
}

