// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParentLogin
 */
export interface ParentLogin {
    /**
     * 
     * @type {string}
     * @memberof ParentLogin
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ParentLogin
     */
    password: string;
}

/**
 * Check if a given object implements the ParentLogin interface.
 */
export function instanceOfParentLogin(value: object): value is ParentLogin {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ParentLoginFromJSON(json: any): ParentLogin {
    return ParentLoginFromJSONTyped(json, false);
}

export function ParentLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentLogin {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function ParentLoginToJSON(json: any): ParentLogin {
    return ParentLoginToJSONTyped(json, false);
}

export function ParentLoginToJSONTyped(value?: ParentLogin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

