// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParentRegister
 */
export interface ParentRegister {
    /**
     * 
     * @type {string}
     * @memberof ParentRegister
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ParentRegister
     */
    password: string;
}

/**
 * Check if a given object implements the ParentRegister interface.
 */
export function instanceOfParentRegister(value: object): value is ParentRegister {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ParentRegisterFromJSON(json: any): ParentRegister {
    return ParentRegisterFromJSONTyped(json, false);
}

export function ParentRegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentRegister {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function ParentRegisterToJSON(json: any): ParentRegister {
    return ParentRegisterToJSONTyped(json, false);
}

export function ParentRegisterToJSONTyped(value?: ParentRegister | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

