// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResponseStatus = {
    Failed: 'FAILED',
    Success: 'SUCCESS'
} as const;
export type ResponseStatus = typeof ResponseStatus[keyof typeof ResponseStatus];


export function instanceOfResponseStatus(value: any): boolean {
    for (const key in ResponseStatus) {
        if (Object.prototype.hasOwnProperty.call(ResponseStatus, key)) {
            if (ResponseStatus[key as keyof typeof ResponseStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResponseStatusFromJSON(json: any): ResponseStatus {
    return ResponseStatusFromJSONTyped(json, false);
}

export function ResponseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseStatus {
    return json as ResponseStatus;
}

export function ResponseStatusToJSON(value?: ResponseStatus | null): any {
    return value as any;
}

export function ResponseStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ResponseStatus {
    return value as ResponseStatus;
}

