// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * TellMom API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StageAssessment
 */
export interface StageAssessment {
    /**
     * Observed | Possible | Not Observed
     * @type {string}
     * @memberof StageAssessment
     */
    status: string;
    /**
     * High | Medium | Low
     * @type {string}
     * @memberof StageAssessment
     */
    confidence: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StageAssessment
     */
    evidence?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof StageAssessment
     */
    reasoning?: string;
}

/**
 * Check if a given object implements the StageAssessment interface.
 */
export function instanceOfStageAssessment(value: object): value is StageAssessment {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    return true;
}

export function StageAssessmentFromJSON(json: any): StageAssessment {
    return StageAssessmentFromJSONTyped(json, false);
}

export function StageAssessmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageAssessment {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'confidence': json['confidence'],
        'evidence': json['evidence'] == null ? undefined : json['evidence'],
        'reasoning': json['reasoning'] == null ? undefined : json['reasoning'],
    };
}

export function StageAssessmentToJSON(json: any): StageAssessment {
    return StageAssessmentToJSONTyped(json, false);
}

export function StageAssessmentToJSONTyped(value?: StageAssessment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'confidence': value['confidence'],
        'evidence': value['evidence'],
        'reasoning': value['reasoning'],
    };
}

